#!/bin/bash

function lineWith {
echo $(grep -s -E $1 /proc/$pid/$2)
}

for pid in $(ps axo pid | sed "1d");
do
	ppid=$(lineWith "^PPid:" status | awk '{print $2}' )
	sum_runtime=$(lineWith "^se.sum_exec_runtime" sched | awk '{print $3}' )
	switches=$(lineWith "^nr_switches" sched | awk '{print $3}' )
	if [ -z $sum_runtime ] || [ -z $switches ]
	then continue
	fi
	art=$(echo $sum_runtime / $switches | bc -l)

	echo "$pid $ppid $art";
done  |
	sort -n --key=2 |
	awk '{print "ProcessID="$1" Parent_ProcessID="$2" Average_Running_Time="$3}' > iv_ans

