#!/bin/bash

ANS="v_ans"

echo "" > $ANS

let lastPpid=0
let artSum=0
let artAmn=0
while read line ;
do
	ppid=$(echo $line | cut -d" " -f2 | cut -d= -f2)
	art=$(echo $line | cut -d" " -f3 | cut -d= -f2)

	if [[ $ppid != $lastPpid ]]
	then
		echo "Average_Sleeping_Children_of_ParentID=$lastPpid is $(echo $artSum / $artAmn | bc -l)" >> $ANS
		artSum=0
		artAmn=0
	fi

	echo $line >> $ANS
	lastPpid=$ppid
	artSum=$(echo $artSum + $art | bc -l)
	artAmn=$(echo $artAmn + 1 | bc -l)
done < iv_ans

echo "Average_Sleeping_Children_of_ParentID=$lastPpid is $(echo $artSum / $artAmn | bc -l)" >> $ANS
