#!/bin/bash

TMP="tmp"
ANS="vii_ans"

echo "" > $TMP
echo "" > $ANS

for pid in $(ps axo pid | sed "1d");
do
	read_mem=$(sudo grep -s -E "^read_bytes" "/proc/$pid/io" | cut -d" " -f2)
	echo "$pid $read_mem" >> $TMP
done;

sleep 10s #for real put 60s

for pid in $(ps axo pid | sed "1d");
do
	cmd=$(cat "/proc/$pid/cmdline")
	read_mem=$(sudo grep -s -E "^read_bytes" "/proc/$pid/io" | cut -d" " -f2)
	prev_read_mem=$(grep -E "^$pid" $TMP | cut -d" " -f2)
	if [[ -z $prev_read_mem ]]
		then prev_read_mem=0
	fi
	delta_mem=$((read_mem - prev_read_mem))
	echo "$pid:$cmd:$delta_mem" >> $ANS
done

sort -t":" -k3 -g $ANS | tail -n3 
