#!/bin/bash

TMP="tmp"
ANS="vii_ans"

echo "" > $TMP
echo "" > $ANS

for pid in $(ps axo pid | sed "1d");
do
	read_mem=$(sudo grep -s read_bytes "/proc/$pid/io" | cut -d" " -f2)
	echo "$pid $read_mem" >> $TMP
done;

sleep 10s #for real put 60s

for pid in $(ps axo pid | sed "1d");
do
	read_mem=$(sudo grep -s read_bytes "/proc/$pid/io" | cut -d" " -f2)
	prev_read_mem=$(grep -E "^$pid" $TMP | cut -d" " -f2)
	if [[ -z $read_mem ]]
	then
		read_mem=0
		cmdL="dead"
	else
		cmdL=$(cat /proc/$pid/cmdline || echo "dead")
	fi
	if [[ -z $prev_read_mem ]]
	then
		prev_read_mem=0
	fi
	delta_mem=$(echo "$read_mem - $prev_read_mem" | bc -l)
	echo "$pid:$cmdL:$delta_mem" >> $ANS
done

sort -t":" -k3 -g $ANS | tail -n3 
